name: UmbrellaProject back-end

on:
  push:
    branches:
      - master
    paths:
      - "back-end/**"

jobs:
  back-end:
    runs-on: ubuntu-latest
    env:
      workdir: ./back-end
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Format
        run: terraform fmt -check
        working-directory: ${{ env.workdir }}

      - name: Terraform Init
        run: terraform init
        working-directory: ${{ env.workdir }}

      - name: AWS Copy Plan
        run: aws s3 cp s3://umbrella-project-albertopmp/back-end/terraform.tfstate terraform.tfstate
        working-directory: ${{ env.workdir }}
        continue-on-error: true # In case infra doesn't already exist

      - name: Terraform Apply
        id: apply
        if: steps.plan.outcome == 'success'
        run: terraform apply -auto-approve -input=false
        env:
          TF_VAR_account_id: ${{ secrets.ACCOUNT_ID }}
        working-directory: ${{ env.workdir }}

      - name: AWS Save Plan
        if: steps.apply.outcome == 'success'
        run: aws s3 cp terraform.tfstate s3://umbrella-project-albertopmp/back-end/terraform.tfstate
        working-directory: ${{ env.workdir }}
