name: UmbrellaProject destroy infra

on:
  workflow_dispatch:
    inputs:
      env:
        description: "Environment"
        required: true
        default: "dev"

jobs:
  destroy:
    runs-on: ubuntu-latest
    env:
      workdir: ./back-end
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init
        working-directory: ${{ env.workdir }}

      - name: AWS Copy Plan
        run: aws s3 cp s3://umbrella-project-albertopmp/back-end/terraform.tfstate terraform.tfstate
        working-directory: ${{ env.workdir }}

      - name: Show Destroy plan
        run: terraform plan -destroy
        env:
          TF_VAR_account_id: ${{ secrets.ACCOUNT_ID }}
        working-directory: ${{ env.workdir }}
        continue-on-error: true

      - name: Destroy resources
        id: destroy
        run: terraform destroy -auto-approve
        env:
          TF_VAR_account_id: ${{ secrets.ACCOUNT_ID }}
        working-directory: ${{ env.workdir }}

      - name: Delete Plan
        if: steps.destroy.outcome == 'success'
        run: aws s3 rm s3://umbrella-project-albertopmp/back-end/terraform.tfstate
        working-directory: ${{ env.workdir }}
